### ISSUE TITLE
Citing this work?

### ISSUE THREAD

**Issue by DethRaid** [roy-a/Roy_VnTokenizer#1]
I'm using this code in an academic project, and I was wondering if you had any paper or website I could cite

**Comment by roy-a** [comment]
Hello, I appreciate that you asked. I didn't convert it to a paper. But you could cite it in your project with the GitHub page url, i.e. https://github.com/roy-a/Roy_VnTokenizer . I presume that's a common practice. Best wishes.

**Comment by roy-a** [comment]
Hope your question was answered. Closing this issue.

**Comment by DethRaid** [comment]
Sorry, didn't see your answer until just now. Yes, you did answer my question. Thanks!

**Comment by roy-a** [comment]
No worries. Best.
